### ISSUE TITLE
Does not compile with perl 5.23.x: Experimental keys on scalar is now forbidden

### ISSUE THREAD

**Issue by eserte** [XTaTIK/XTaTIK#147]
See subject. Test fails like this:
```
#   Failed test 'XTaTIK/Utilities/Misc.pm loaded ok'
#   at t/00-compile.t line 66.
#          got: '65280'
#     expected: '0'
Experimental keys on scalar is now forbidden at /home/cpansand/.cpan/build/2015090718/XTaTIK-0.002001-LosRk9/blib/lib/XTaTIK/Utilities/Misc.pm line 18.
Compilation failed in require at -e line 1.

#   Failed test 'XTaTIK/Utilities/ToadFarmer.pm loaded ok'
#   at t/00-compile.t line 66.
#          got: '65280'
#     expected: '0'
Experimental keys on scalar is now forbidden at /home/cpansand/.cpan/build/2015090718/XTaTIK-0.002001-LosRk9/blib/lib/XTaTIK/Utilities/Misc.pm line 18, <DATA> line 2231.
Compilation failed in require at /home/cpansand/.cpan/build/2015090718/XTaTIK-0.002001-LosRk9/blib/lib/XTaTIK/Utilities/ToadFarmer.pm line 9, <DATA> line 2231.
BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2015090718/XTaTIK-0.002001-LosRk9/blib/lib/XTaTIK/Utilities/ToadFarmer.pm line 9, <DATA> line 2231.
Compilation failed in require at -e line 1, <DATA> line 2231.
# Looks like you failed 2 tests of 29.
t/00-compile.t ................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/29 subtests 
```

**Comment by zoffixznet** [comment]
Thanks a lot!
